stripe:
      public_key: pk_test_51KdvoQDYhAELQbJDI8G1uZxk8QQUgUtWb2jIZAJzGSKMf6wxPuCQLhCYHKep1vO0dgnYJgt0wpuGAxsBLV1lV5CT00D350DfnT
      secret_key: sk_test_51KdvoQDYhAELQbJD9clXJsQ0vO6CxF2kANIJYVcob92JmU9AbPxxHatPmORxdmPHSxMT959vpFy76zULmGxoLScZ00OLcryl0v
webhook_signing_secret:
pricing:
    monthly:
        monthly: price_1NdWeBDYhAELQbJDGZ1NCyJE
        yearly: price_1NdWeBDYhAELQbJDD9bFgBS4